extends:
  - "@commitlint/config-conventional"

rules:
  "type-enum":
    - 2
    - always
    - - init # init or manifest configs.
      - feat # add new features.
      - perf # optimize for better performance.
      - fix # fix existing bugs.
      - doc # edit docs or comments.
      - other # other special commits.
